"""Domain package containing pure models and exceptions."""

from patangoma.domain.exceptions import (
    AudioFileError,
    AudioFileNotFoundError,
    CorruptAudioFileError,
    InvalidAudioFileError,
    PataNgomaError,
    PlanError,
    PlanValidationError,
    ProviderAuthenticationError,
    ProviderError,
    ProviderRateLimitError,
    ProviderUnavailableError,
    RollbackError,
    TagReadError,
    TagWriteError,
    UnsupportedAudioFormatError,
)
from patangoma.domain.models import (
    AuditRecord,
    ConfidenceLevel,
    FieldDiffStatus,
    MatchResult,
    MetadataCandidate,
    QueryParameters,
    ScoreBreakdown,
    TagFieldDiff,
    TagPlan,
    TrackMetadata,
)

__all__ = [
    "AudioFileError",
    "AudioFileNotFoundError",
    "AuditRecord",
    "ConfidenceLevel",
    "CorruptAudioFileError",
    "FieldDiffStatus",
    "InvalidAudioFileError",
    "MatchResult",
    "MetadataCandidate",
    "PataNgomaError",
    "PlanError",
    "PlanValidationError",
    "ProviderAuthenticationError",
    "ProviderError",
    "ProviderRateLimitError",
    "ProviderUnavailableError",
    "QueryParameters",
    "RollbackError",
    "ScoreBreakdown",
    "TagFieldDiff",
    "TagPlan",
    "TagReadError",
    "TagWriteError",
    "TrackMetadata",
    "UnsupportedAudioFormatError",
]
